//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaAlbum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerConfigure
    {
        public int CustomerID { get; set; }
        public int ParentCategoryID { get; set; }
        public int SubCategoryID { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblParentCategory tblParentCategory { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
