//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaAlbum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBanner
    {
        public int BannerID { get; set; }
        public string BannerImage { get; set; }
        public string BannerHeading { get; set; }
        public string BannerDescription { get; set; }
    }
}
