//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaAlbum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGallery
    {
        public long GalleryID { get; set; }
        public int SubCategoryID { get; set; }
        public int CustomerID { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
