//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaAlbum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortfolio
    {
        public int PortfolioID { get; set; }
        public string PortfolioName { get; set; }
        public string SmallDescription { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
