//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaAlbum.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class tblParentCategory
    {
        private InstaAlbumEntities db = new InstaAlbumEntities();

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblParentCategory()
        {
            this.CustomerConfigures = new HashSet<CustomerConfigure>();
            this.tblSubCategories = new HashSet<tblSubCategory>();
        }
    
        public int ParentCategoryID { get; set; }
        public string ParentCategoryName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerConfigure> CustomerConfigures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubCategory> tblSubCategories { get; set; }

        public string getCatName(int id)
        {
            tblParentCategory cat = db.tblParentCategories.SingleOrDefault(c => c.ParentCategoryID == id);
            if (cat != null && cat.ParentCategoryName.Length > 0)
                return cat.ParentCategoryName;
            else
                return "";
        }
    }
}
