//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaAlbum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhotographer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPhotographer()
        {
            this.tblExposings = new HashSet<tblExposing>();
        }
    
        public int PhotographerID { get; set; }
        public int BranchID { get; set; }
        public string PhotographerName { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string ProfilePic { get; set; }
        public string Address { get; set; }
        public string CameraName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsFreelancer { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExposing> tblExposings { get; set; }
    }
}
